// ignore_for_file: avoid_print
//
// AD-15's literal ban, as a build-time check: no string literal may reach a
// widget, and no runtime sentence may be assembled by concatenation.
//
// The shipped ARB (`lib/l10n/app_es.arb`) is the single string table;
// `lib/strings/` holds only generated accessors. So this scan bans every
// string literal in `lib/**.dart` outside the exact generated accessors and
// the four named font/format strings in `lib/ui/tokens.dart`. Generated files
// are marked and regenerated byte-for-byte; extra files under `lib/strings/`
// fail. Directive URIs (import/export/part,
// through the terminating `;`, across formatter-wrapped lines) are exempt,
// as in check_core_purity.dart. A separate scan rejects `AppStrings` accessor
// concatenation, which otherwise contains no literal to find. The sole
// permitted interpolation is one atomic numeral or proper name substituted
// into an otherwise fixed ARB sentence through a generated accessor.
//
// Output contract (Story 1.1 AC 2): one `file:line: message` line per
// finding, exit 1 when any finding exists.
import 'dart:io';

import 'check_core_purity.dart';

const String generatedStringsHeader = '// Generated by gen_l10n. Do not edit.';

/// A string literal found in source, with its 1-based start line.
class LiteralFinding {
  const LiteralFinding(
    this.file,
    this.line, {
    this.message = 'string literal reaches lib/ (AD-15)',
  });

  final String file;
  final int line;
  final String message;

  @override
  String toString() => '$file:$line: $message';
}

bool _isIdentPart(int code, String? c) {
  if (c == null) {
    return false;
  }
  return c == '_' ||
      (c.compareTo('a') >= 0 && c.compareTo('z') <= 0) ||
      (c.compareTo('A') >= 0 && c.compareTo('Z') <= 0) ||
      (c.compareTo('0') >= 0 && c.compareTo('9') <= 0);
}

bool _lineStartsWithDirective(String source, int from) {
  var k = from;
  while (k < source.length && (source[k] == ' ' || source[k] == '\t')) {
    k++;
  }
  for (final word in const ['import', 'export', 'part']) {
    if (source.startsWith(word, k) &&
        !_isIdentPart(
          0,
          k + word.length < source.length ? source[k + word.length] : null,
        )) {
      return true;
    }
  }
  return false;
}

/// Locates the span of every non-directive string literal in [source],
/// skipping comments (line, and nested block), raw/triple strings, escape
/// sequences — and `${…}` interpolation bodies, whose braces nest and
/// whose embedded quotes belong to the body, not the enclosing literal —
/// the same lexing judgement `check_core_purity.maskCommentsAndStrings`
/// applies. Directive URIs are exempt. Malformed input (an unterminated
/// single-line string) recovers at the newline so the rest of the file
/// still scans.
List<(int, int)> stringLiteralSpans(String source) {
  final spans = <(int, int)>[];
  var inDirective = false;
  var lineStartHandled = -1;
  var i = 0;

  while (i < source.length) {
    final c = source[i];
    final next = i + 1 < source.length ? source[i + 1] : '';

    if (c == '/' && next == '/') {
      while (i < source.length && source[i] != '\n') {
        i++;
      }
    } else if (c == '/' && next == '*') {
      var depth = 1;
      i += 2;
      while (i < source.length && depth > 0) {
        if (source[i] == '/' && i + 1 < source.length && source[i + 1] == '*') {
          depth++;
          i += 2;
        } else if (source[i] == '*' &&
            i + 1 < source.length &&
            source[i + 1] == '/') {
          depth--;
          i += 2;
        } else {
          i++;
        }
      }
    } else if (c == ';') {
      inDirective = false;
      i++;
    } else if (c != '\n' &&
        (i == 0 || source[i - 1] == '\n') &&
        !inDirective &&
        lineStartHandled != i) {
      // Line-start directive detection: set state once per line start, then
      // re-examine this character from the top of the loop (a comment or a
      // string opening on the same line must be judged in that state).
      lineStartHandled = i;
      inDirective = _lineStartsWithDirective(source, i);
    } else if (c == "'" || c == '"') {
      var raw = false;
      if (i > 0 &&
          source[i - 1] == 'r' &&
          (i == 1 || !_isIdentPart(0, source[i - 2]))) {
        raw = true;
      }
      final triple = next == c && (i + 2 < source.length && source[i + 2] == c);
      final start = i;
      i += triple ? 3 : 1;
      var unterminated = false;
      var interpDepth = 0;
      while (true) {
        if (i >= source.length) {
          unterminated = true;
          break;
        }
        final sc = source[i];
        if (!raw && sc == r'\' && interpDepth == 0) {
          i += 2;
          continue;
        }
        // `${…}` bodies are code, not string content: braces nest, quotes
        // inside are consumed by the body (the enclosing literal is already
        // a finding), and a newline inside a multi-line interpolation does
        // not terminate a single-line string.
        if (!raw &&
            sc == r'$' &&
            i + 1 < source.length &&
            source[i + 1] == '{') {
          interpDepth++;
          i += 2;
          continue;
        }
        if (interpDepth > 0) {
          if (sc == '{') {
            interpDepth++;
          } else if (sc == '}') {
            interpDepth--;
          }
          i++;
          continue;
        }
        if (sc == '\n' && !triple) {
          unterminated = true;
          break;
        }
        if (sc == c) {
          if (triple) {
            final a = i + 1 < source.length ? source[i + 1] : '';
            final b = i + 2 < source.length ? source[i + 2] : '';
            if (a == c && b == c) {
              i += 3;
              break;
            }
            i++;
          } else {
            i++;
            break;
          }
        } else {
          i++;
        }
      }
      if (!unterminated && !inDirective) {
        spans.add((start, i));
      }
    } else {
      i++;
    }
  }
  return spans;
}

int _lineOf(String text, int index) =>
    '\n'.allMatches(text.substring(0, index)).length + 1;

/// Scans one file's source for banned string literals.
List<LiteralFinding> scanSource({
  required String file,
  required String source,
}) {
  final findings = stringLiteralSpans(source)
      .map((span) => LiteralFinding(file, _lineOf(source, span.$1)))
      .toList();
  final masked = maskCommentsAndStrings(source);
  final bindings = <String>{};
  final bindingPattern = RegExp(
    r'\bAppStrings\s+([A-Za-z_]\w*)|'
    r'\b(?:final|var)\s+([A-Za-z_]\w*)\s*=\s*AppStrings\.of\s*\(',
  );
  for (final match in bindingPattern.allMatches(masked)) {
    bindings.add(match.group(1) ?? match.group(2)!);
  }

  final bindingAccess = bindings.isEmpty
      ? null
      : r'(?:' +
            bindings.map(RegExp.escape).join('|') +
            r')\s*\.\s*[A-Za-z_]\w*(?:\s*\([^;\n]*?\))?';
  const directAccess =
      r'AppStrings\.of\s*\([^;\n]*?\)\s*\.\s*[A-Za-z_]\w*'
      r'(?:\s*\([^;\n]*?\))?';
  final access = bindingAccess == null
      ? '(?:$directAccess)'
      : '(?:$bindingAccess|$directAccess)';

  // A sentence made from two generated accessors contains no literal, so it
  // needs its own guard. One accessor call with an atomic placeholder remains
  // legal; combining two localized messages never does.
  final concatenation = RegExp('$access\\s*\\+\\s*$access');
  for (final match in concatenation.allMatches(masked)) {
    findings.add(
      LiteralFinding(
        file,
        _lineOf(masked, match.start),
        message:
            'localized accessors are concatenated at runtime — use one fixed '
            'ARB sentence (AD-15)',
      ),
    );
  }
  findings.sort((a, b) => a.line.compareTo(b.line));
  return findings;
}

List<LiteralFinding> _scanTokenFile(File file) {
  final source = file.readAsStringSync();
  final spans = stringLiteralSpans(source);
  final findings = <LiteralFinding>[];
  const allowedNames = {'lora', 'lexend', 'shortDateFormat', 'durationFormat'};
  for (final span in spans) {
    final lineStart = source.lastIndexOf('\n', span.$1 - 1) + 1;
    final lineEnd = source.indexOf('\n', span.$2);
    final line = source.substring(
      lineStart,
      lineEnd == -1 ? source.length : lineEnd,
    );
    final declaration = RegExp(r'^\s*static const String ([A-Za-z_]\w*)\s*=')
        .firstMatch(line);
    if (declaration == null || !allowedNames.contains(declaration.group(1))) {
      findings.add(LiteralFinding(file.path, _lineOf(source, span.$1)));
    }
  }
  return findings;
}

/// Walks every `.dart` file under [libDir]. Only the exact generated accessor
/// files and the four named token strings are exempt.
List<LiteralFinding> scanLib(Directory libDir) {
  final findings = <LiteralFinding>[];
  final files = <File>[];
  final stringsDir = '${libDir.path}/strings';
  final tokenFile = '${libDir.path}/ui/tokens.dart';
  final generatedNames = {'app_strings.dart', 'app_strings_es.dart'};
  void collect(Directory dir) {
    for (final entity in dir.listSync(followLinks: false)) {
      if (entity is Directory) {
        if (entity.path == stringsDir) {
          final seen = <String>{};
          for (final generated in entity.listSync(followLinks: false)) {
            if (generated is! File || !generated.path.endsWith('.dart')) {
              continue;
            }
            final name = generated.uri.pathSegments.last;
            seen.add(name);
            final source = generated.readAsStringSync();
            if (!generatedNames.contains(name) ||
                !source.startsWith(generatedStringsHeader)) {
              findings.add(
                LiteralFinding(
                  generated.path,
                  1,
                  message:
                      'lib/strings/ may contain only marked gen_l10n output '
                      '(AD-15)',
                ),
              );
            }
          }
          for (final missing in generatedNames.difference(seen)) {
            findings.add(
              LiteralFinding(
                '${entity.path}/$missing',
                1,
                message: 'generated localization accessor is missing (AD-15)',
              ),
            );
          }
          continue;
        }
        collect(entity);
      } else if (entity is File && entity.path.endsWith('.dart')) {
        if (entity.path == tokenFile) {
          findings.addAll(_scanTokenFile(entity));
          continue;
        }
        files.add(entity);
      }
    }
  }

  collect(libDir);
  files.sort((a, b) => a.path.compareTo(b.path));
  for (final file in files) {
    findings.addAll(
      scanSource(file: file.path, source: file.readAsStringSync()),
    );
  }
  return findings;
}

bool _sameBytes(List<int> left, List<int> right) {
  if (left.length != right.length) {
    return false;
  }
  for (var i = 0; i < left.length; i++) {
    if (left[i] != right[i]) {
      return false;
    }
  }
  return true;
}

Future<List<LiteralFinding>> _generatedDriftFindings(String repoRoot) async {
  final root = repoRoot.isEmpty ? Directory.current.path : repoRoot;
  if (!File('$root/l10n.yaml').existsSync() ||
      !File('$root/pubspec.yaml').existsSync()) {
    return const [];
  }
  final paths = [
    '$root/lib/strings/app_strings.dart',
    '$root/lib/strings/app_strings_es.dart',
  ];
  final before = <String, List<int>?>{
    for (final path in paths)
      path: File(path).existsSync() ? File(path).readAsBytesSync() : null,
  };
  void restoreOriginals() {
    for (final path in paths) {
      final file = File(path);
      final original = before[path];
      if (original == null) {
        if (file.existsSync()) {
          file.deleteSync();
        }
      } else {
        file.writeAsBytesSync(original, flush: true);
      }
    }
  }

  final result = await Process.run('flutter', const [
    'gen-l10n',
  ], workingDirectory: root);
  if (result.exitCode != 0) {
    restoreOriginals();
    return [
      LiteralFinding(
        '$root/l10n.yaml',
        1,
        message: 'flutter gen-l10n failed: ${result.stderr}',
      ),
    ];
  }

  final findings = <LiteralFinding>[];
  for (final path in paths) {
    final file = File(path);
    final original = before[path];
    final generated = file.existsSync() ? file.readAsBytesSync() : null;
    final changed =
        original == null ||
        generated == null ||
        !_sameBytes(original, generated);
    if (changed) {
      findings.add(
        LiteralFinding(
          path,
          1,
          message:
              'generated localization accessor is stale; run flutter '
              'gen-l10n (AD-15)',
        ),
      );
    }
  }
  restoreOriginals();
  return findings;
}

Future<int> runCheck([String repoRoot = '']) async {
  final libDir = Directory(repoRoot.isEmpty ? 'lib' : '$repoRoot/lib');
  if (!libDir.existsSync()) {
    stderr.writeln('lib/ not found at ${libDir.path}');
    return 2;
  }
  final findings = [
    ...await _generatedDriftFindings(repoRoot),
    ...scanLib(libDir),
  ];
  for (final finding in findings) {
    print(finding);
  }
  if (findings.isNotEmpty) {
    print(
      'no-literal-strings check FAILED: ${findings.length} finding(s) — '
      'every string enters through lib/l10n/app_es.arb (AD-15)',
    );
    return 1;
  }
  print('no-literal-strings check passed');
  return 0;
}

Future<void> main(List<String> args) async {
  exit(await runCheck(args.isEmpty ? '' : args.first));
}
