// ignore_for_file: avoid_print
//
// The catalogue lookup-table generator (AD-16, conventions — i18n): reads
// the shipped catalogue asset and the single string table, derives each
// entry's ARB key from its permanent id (`regar-una-planta` →
// `catalogueRegarUnaPlanta`), and emits `lib/catalogue/catalogue_names.g.dart`
// — the static id→AppStrings getter table plus the asset-path constant.
//
// No runtime key assembly exists anywhere (SPINE conventions — i18n): the
// loader resolves names only through this generated table, so every key is
// statically present in the ARB and audited like all copy (AD-15). The
// generator fails on any missing derived key, on two ids deriving the same
// key, and on an orphaned `catalogue*` ARB key no asset entry derives —
// dead copy cannot accumulate silently.
//
// Output contract: one `file:line: message` line per finding, exit 1 when
// any finding exists, exit 2 when an input file is missing. Registered
// under `make codegen` / `make codegen-check` (NFR20).
import 'dart:io';

import 'package:core/catalogue/catalogue.dart';
import 'package:core/catalogue/strict_json.dart';

import 'catalogue_shared.dart';

const String assetPath = 'assets/evergreen/catalogue.json';
const String arbPath = 'lib/l10n/app_es.arb';
const String outputPath = 'lib/catalogue/catalogue_names.g.dart';

/// Derives the ARB key from a permanent catalogue id: kebab-case slug →
/// PascalCase, prefixed `catalogue` (`regar-una-planta` →
/// `catalogueRegarUnaPlanta`).
String deriveCatalogueKey(String id) =>
    'catalogue${id.split('-').map((word) => word.isEmpty ? word : word[0].toUpperCase() + word.substring(1)).join()}';

int _entryLine(String assetText, String id) {
  final probe = assetText.indexOf('"$id"');
  return probe == -1 ? 1 : lineOf(assetText, probe);
}

int _arbKeyLine(String arbText, String key) {
  final probe = arbText.indexOf('"$key"');
  return probe == -1 ? 1 : lineOf(arbText, probe);
}

class GenerationResult {
  const GenerationResult({required this.findings, required this.output});

  /// One `file:line: message` per problem; empty means the output is good.
  final List<String> findings;

  /// The generated file's source, valid whenever findings is empty.
  final String? output;
}

/// Computes the generated table from the raw asset and ARB texts.
GenerationResult generateLookup({
  required String assetText,
  required String arbText,
}) {
  final findings = <String>[];
  final catalogue = _parseAsset(assetText, findings);
  if (catalogue == null) {
    return GenerationResult(findings: findings, output: null);
  }
  final Object? arbDecoded = _decodeOrReport(arbPath, arbText, findings);
  if (arbDecoded is! Map<String, dynamic>) {
    if (findings.isEmpty) {
      findings.add('$arbPath:1: top level is not a JSON object');
    }
    return GenerationResult(findings: findings, output: null);
  }

  final lines = <String>[
    '// GENERATED CODE - DO NOT MODIFY BY HAND',
    '//',
    '// Generated by tool/gen_catalogue_lookup.dart from',
    '// $assetPath and $arbPath.',
    '// Every catalogue name resolves through a statically present ARB',
    '// key; none is assembled at runtime (AD-16, AD-15).',
    '',
    "import '../strings/app_strings.dart';",
    '',
    '/// The bundle path of the shipped Evergreen catalogue (AD-16).',
    "const String catalogueAssetPath = '$assetPath';",
    '',
    '/// The static catalogue id → AppStrings getter table. The shell loader',
    '/// resolves each entry’s Spanish name through it at load time and hands',
    '/// the core inert data — no key is ever computed at runtime.',
    'final Map<String, String Function(AppStrings strings)> catalogueNameOf =',
    '    Map.unmodifiable(<String, String Function(AppStrings strings)>{',
  ];

  final keyOwner = <String, String>{};
  for (final entry in catalogue.entries) {
    final id = entry.id;
    final key = deriveCatalogueKey(id);
    final owner = keyOwner[key];
    if (owner != null) {
      findings.add(
        '$assetPath:${_entryLine(assetText, id)}: ids "$owner" and "$id" '
        'both derive ARB key "$key" — one of them needs a different slug '
        '(AD-16)',
      );
      continue;
    }
    keyOwner[key] = id;
    final value = arbDecoded[key];
    if (value is! String || value.trim().isEmpty) {
      findings.add(
        '$arbPath:${_arbKeyLine(arbText, key)}: derived ARB key "$key" '
        'for entry "$id" must hold a non-blank string value (AD-16)',
      );
      continue;
    }
    final metadata = arbDecoded['@$key'];
    if (metadata is! Map<String, dynamic> ||
        metadata['description'] is! String ||
        (metadata['description'] as String).trim().isEmpty) {
      findings.add(
        '$arbPath:${_arbKeyLine(arbText, '@$key')}: derived ARB key "$key" '
        'needs a non-blank "@$key.description" (AD-16)',
      );
      continue;
    }
    lines.add("  '$id': (strings) => strings.$key,");
  }
  final orphanedKeys =
      arbDecoded.keys
          .where(
            (key) =>
                !key.startsWith('@') &&
                key.startsWith('catalogue') &&
                !keyOwner.containsKey(key),
          )
          .toList()
        ..sort();
  for (final key in orphanedKeys) {
    findings.add(
      '$arbPath:${_arbKeyLine(arbText, key)}: orphaned catalogue key "$key" — '
      'no asset entry derives it; dead copy cannot accumulate (AD-15, AD-16)',
    );
  }
  lines.add('});');
  findings.sort();
  return GenerationResult(
    findings: findings,
    output: findings.isEmpty ? lines.join('\n') : null,
  );
}

Object? _decodeOrReport(String file, String source, List<String> findings) {
  try {
    return strictJsonDecode(source);
  } on StrictJsonFormatException catch (error) {
    findings.add(
      '$file:${lineForFormatException(source, error)}: ${error.message}',
    );
    return null;
  }
}

Catalogue? _parseAsset(String source, List<String> findings) {
  try {
    return parseCatalogue(source, nameOf: (_) => '');
  } on StrictJsonFormatException catch (error) {
    findings.add(
      '$assetPath:${lineForFormatException(source, error)}: '
      '${error.message}',
    );
    return null;
  } on FormatException catch (error) {
    findings.add(
      '$assetPath:${lineForEntryError(source, error.message)}: '
      '${error.message}',
    );
    return null;
  }
}

/// Runs the generation against [repoRoot], writing the output file (and
/// formatting it, so a fresh generation is byte-identical to the committed
/// one). Returns the process exit code.
Future<int> runGeneration([String repoRoot = '']) async {
  final root = repoRoot.isEmpty ? '' : '$repoRoot/';
  final asset = File('$root$assetPath');
  final arb = File('$root$arbPath');
  if (!asset.existsSync()) {
    stderr.writeln('asset not found at ${asset.path}');
    return 2;
  }
  if (!arb.existsSync()) {
    stderr.writeln('ARB not found at ${arb.path}');
    return 2;
  }
  final result = generateLookup(
    assetText: asset.readAsStringSync(),
    arbText: arb.readAsStringSync(),
  );
  for (final finding in result.findings) {
    print(finding);
  }
  if (result.findings.isNotEmpty) {
    print(
      'catalogue lookup generation FAILED: ${result.findings.length} '
      'finding(s) — every asset entry needs its derived ARB key, no two '
      'ids may share one, and no catalogue key may be orphaned (AD-16)',
    );
    return 1;
  }
  final output = File('$root$outputPath');
  Directory(output.parent.path).createSync(recursive: true);
  // ignore: unnecessary_string_interpolations — the trailing newline is
  // part of the emitted file, not of the generated source string.
  output.writeAsStringSync('${result.output}\n');
  final format = await Process.run('dart', [
    'format',
    output.path,
  ], runInShell: false);
  if (format.exitCode != 0) {
    stderr.writeln('dart format failed on ${output.path}: ${format.stderr}');
    return 2;
  }
  print('catalogue lookup table written to ${output.path}');
  return 0;
}

Future<void> main(List<String> args) async {
  exit(await runGeneration(args.isEmpty ? '' : args.first));
}
