// Generated by gen_l10n. Do not edit.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'app_strings.dart';

// ignore_for_file: type=lint

/// The translations for Spanish Castilian (`es`).
class AppStringsEs extends AppStrings {
  AppStringsEs([String locale = 'es']) : super(locale);

  @override
  String get actionDone => 'Hecho';

  @override
  String get completionAcknowledgement => '¡Buen trabajo!';

  @override
  String get actionRescueOrSkip => 'Otra más fácil / Ahora no';

  @override
  String pocketTrigger(int minutes) {
    String _temp0 = intl.Intl.pluralLogic(
      minutes,
      locale: localeName,
      other: 'Tengo $minutes minutos ahora',
      one: 'Tengo un minuto ahora',
    );
    return '$_temp0';
  }

  @override
  String get sampleTask => 'Despeja la mesa del salón';

  @override
  String get zoneZ1 => 'Cocina y despensa';

  @override
  String get zoneZ2 => 'Baños';

  @override
  String get zoneZ3 => 'Dormitorios';

  @override
  String get zoneZ4 => 'Salón y zonas comunes';

  @override
  String get zoneZ5 => 'Entrada, lavadero y exteriores';

  @override
  String durationMinutes(int minutes) {
    return '$minutes min';
  }

  @override
  String durationSeconds(int seconds) {
    return '$seconds s';
  }

  @override
  String get destinationKeep => 'Quedármelo';

  @override
  String get destinationDonate => 'Donar o vender';

  @override
  String get destinationRelease => 'Tirar o soltar';

  @override
  String get liberatedVolume => '≈ 3 cajas liberadas';

  @override
  String get weeklySelfReportQuestion =>
      'Esta semana, ¿cuánto te ha agobiado la casa?';

  @override
  String get ambientInvitationStorage =>
      'Si no tienes nada que hacer, tengo un trabajillo para ti';

  @override
  String get ambientInvitationImprovement =>
      'Hay algo en la casa que se puede mejorar';

  @override
  String get ambientInvitationPocket => 'Con solo 15 minutos podemos avanzar';

  @override
  String get ambientInvitationTaskChange =>
      'Si necesitas cambiar de tarea, te puedo ayudar';

  @override
  String get ambientInvitationBreak =>
      'Te puedes tomar un respiro de 15 minutos haciendo otras cosas';

  @override
  String get checkpointStop => 'Nada más por el momento';

  @override
  String get checkpointContinue => 'Quiero seguir';

  @override
  String get warmReturnGreeting => 'Siempre a tu disposición';

  @override
  String get poolExhaustedClose =>
      'por hoy no hay nada más que merezca la pena';

  @override
  String get noSlicerNoKey =>
      'No hay clave de IA guardada. Crear un proyecto a partir de una foto necesita una; puedes añadirla en Ajustes.';

  @override
  String get noSlicerInvalidKey =>
      'La clave guardada no es válida. Puedes revisarla en Ajustes.';

  @override
  String get noSlicerQuotaExhausted =>
      'El crédito de la clave se ha agotado. Se repone en la cuenta del proveedor, no en la app.';

  @override
  String get noSlicerUnreachable =>
      'El servicio de IA no responde ahora mismo. Puedes intentarlo más tarde.';

  @override
  String get noSlicerOffline =>
      'El móvil está sin conexión. Los servicios que usan IA no son accesibles.';

  @override
  String get noSlicerConsentDeclined => 'La foto no se ha enviado.';

  @override
  String get personInFrame =>
      'Se ve una persona en la foto, así que no se ha enviado a ningún sitio. Puedes repetirla sin nadie en el encuadre.';

  @override
  String consentGateBody(String provider) {
    return 'La foto se procesará por $provider para obtener las tareas necesarias.';
  }

  @override
  String get consentGateSend => 'Enviar la foto';

  @override
  String get consentGateDecline => 'No enviarla';

  @override
  String get scanWaitTitle => 'Creando tareas';

  @override
  String get noSlicerExit => 'Anotarlo';

  @override
  String get newProjectLink => 'Nuevo proyecto';

  @override
  String get actionStop => 'Quiero parar';

  @override
  String get settingsWayOut => 'Ajustes';

  @override
  String get settingsGroupYourDay => 'Tu día';

  @override
  String get settingsTimeBag => 'Bolsa de tiempo';

  @override
  String get genesisAnalyze => 'Analizar';

  @override
  String get genesisBack => 'Volver';

  @override
  String get curationInvitation => 'Ajustar grupos de tareas';

  @override
  String get rewardWithoutPhoto => 'Un trabajo estupendo';

  @override
  String get rewardLabelBefore => 'Antes';

  @override
  String get rewardLabelAfter => 'Después';

  @override
  String get snowballDismissAcknowledgement => 'Está bien así.';

  @override
  String get energyCheckInQuestion => '¿Cuánta energía tienes hoy?';

  @override
  String get selfReportScaleLow => 'Nada';

  @override
  String get selfReportScaleHigh => 'Muchísimo';

  @override
  String get captureTitle => 'Un rincón de la casa';

  @override
  String get captureHelper =>
      'Una cosa que se pueda señalar con la mano: un cajón, una estantería, una silla, un rincón.';

  @override
  String get captureExample => 'Vaciar la caja de la entrada';

  @override
  String get captureFieldPlaceholder => 'Escríbelo o dilo en voz alta';

  @override
  String get dictationListening => 'Escuchando…';

  @override
  String get captureSave => 'Guardar';

  @override
  String get captureDiscard => 'Descartar';

  @override
  String get catalogueSacarBrilloAlFregadero => 'Sacar brillo al fregadero';

  @override
  String get catalogueHacerLaCama => 'Hacer la cama';

  @override
  String get catalogueAbrirUnaVentanaAVentilar =>
      'Abrir una ventana a ventilar';

  @override
  String get catalogueRecoger3CosasDelSuelo => 'Recoger 3 cosas del suelo';

  @override
  String get catalogueColgarLaToalla => 'Colgar la toalla';

  @override
  String get catalogueRepasarElEspejoDelBanoConLaToallaUsada =>
      'Repasar el espejo del baño con la toalla usada';

  @override
  String get catalogueMeterEnElLavavajillasLoQueHayEnElFregadero =>
      'Meter en el lavavajillas lo que hay en el fregadero';

  @override
  String get catalogueArrancarUnaLavadora => 'Arrancar una lavadora';

  @override
  String get catalogueSacarLaBasuraAlRellano => 'Sacar la basura al rellano';

  @override
  String get catalogueGuardarLosZapatosDeLaEntrada =>
      'Guardar los zapatos de la entrada';

  @override
  String get catalogueRegarUnaPlanta => 'Regar una planta';

  @override
  String get catalogueDespejarLaMesitaDeNoche => 'Despejar la mesita de noche';

  @override
  String get catalogueBajarLaTapaYRepasarElBordeDelInodoro =>
      'Bajar la tapa y repasar el borde del inodoro';

  @override
  String get catalogueVaciarLaPapeleraDelBano => 'Vaciar la papelera del baño';

  @override
  String get cataloguePonerLaMesa => 'Poner la mesa';

  @override
  String get catalogueRecogerLaMesa => 'Recoger la mesa';

  @override
  String get catalogueVaciarElLavavajillas => 'Vaciar el lavavajillas';

  @override
  String get catalogueRepasarLaEncimera => 'Repasar la encimera';

  @override
  String get catalogueLimpiarLaPlaca => 'Limpiar la placa';

  @override
  String get catalogueBarrerBajoLaMesaDelComedor =>
      'Barrer bajo la mesa del comedor';

  @override
  String get cataloguePasarLaMopaPorLaCocina => 'Pasar la mopa por la cocina';

  @override
  String get catalogueRepasarElLavaboYLosGrifos =>
      'Repasar el lavabo y los grifos';

  @override
  String get catalogueDoblarCincoPrendas => 'Doblar cinco prendas';

  @override
  String get catalogueGuardarLaCompraQueQuedoFuera =>
      'Guardar la compra que quedó fuera';

  @override
  String get catalogueOrdenarLosCojinesYLaMantaDelSofa =>
      'Ordenar los cojines y la manta del sofá';

  @override
  String get catalogueVaciarYAclararElCuboDeReciclaje =>
      'Vaciar y aclarar el cubo de reciclaje';

  @override
  String get catalogueRecogerLaMesaDeCentro => 'Recoger la mesa de centro';

  @override
  String get catalogueSacarLaBasuraOrganica => 'Sacar la basura orgánica';

  @override
  String get catalogueLavarLosPlatosAMano => 'Lavar los platos a mano';

  @override
  String get catalogueDejarLaCocinaCerrada => 'Dejar la cocina cerrada';

  @override
  String get catalogueTenderLaColada => 'Tender la colada';

  @override
  String get catalogueDoblarYGuardarUnaColada => 'Doblar y guardar una colada';

  @override
  String get catalogueRecogerElSalonEntero => 'Recoger el salón entero';

  @override
  String get catalogueOrdenarLaEntradaYElRecibidor =>
      'Ordenar la entrada y el recibidor';

  @override
  String get cataloguePasarLaAspiradoraALaCocina =>
      'Pasar la aspiradora a la cocina';

  @override
  String get catalogueFregarElSueloDeLaCocina => 'Fregar el suelo de la cocina';

  @override
  String get catalogueDesengrasarLaCampanaExtractora =>
      'Desengrasar la campana extractora';

  @override
  String get catalogueVaciarUnaBaldaDelFrigorificoYTirarLoCaducado =>
      'Vaciar una balda del frigorífico y tirar lo caducado';

  @override
  String get catalogueRepasarLosAzulejosDetrasDeLaPlaca =>
      'Repasar los azulejos detrás de la placa';

  @override
  String get catalogueLimpiarElMicroondasPorDentro =>
      'Limpiar el microondas por dentro';

  @override
  String get catalogueLimpiarElFrigorificoPorFueraYLosTiradores =>
      'Limpiar el frigorífico por fuera y los tiradores';

  @override
  String get catalogueOrdenarElCajonDeLosCubiertos =>
      'Ordenar el cajón de los cubiertos';

  @override
  String get catalogueLimpiarLaDuchaOLaBanera => 'Limpiar la ducha o la bañera';

  @override
  String get catalogueFregarElSueloDelBano => 'Fregar el suelo del baño';

  @override
  String get catalogueOrdenarElArmarioDelBanoYTirarLoCaducado =>
      'Ordenar el armario del baño y tirar lo caducado';

  @override
  String get catalogueLimpiarElInodoro => 'Limpiar el inodoro';

  @override
  String get catalogueLimpiarElEspejoYLosGrifos =>
      'Limpiar el espejo y los grifos';

  @override
  String get catalogueCambiarLasToallas => 'Cambiar las toallas';

  @override
  String get catalogueDestaparElDesagueDeLaDucha =>
      'Destapar el desagüe de la ducha';

  @override
  String get catalogueCambiarLasSabanas => 'Cambiar las sábanas';

  @override
  String get cataloguePasarLaAspiradoraAlDormitorio =>
      'Pasar la aspiradora al dormitorio';

  @override
  String get catalogueAspirarDebajoDeLaCama => 'Aspirar debajo de la cama';

  @override
  String get catalogueVaciarYAirearUnaBaldaDelArmario =>
      'Vaciar y airear una balda del armario';

  @override
  String get catalogueQuitarElPolvoDeLasSuperficies =>
      'Quitar el polvo de las superficies';

  @override
  String get catalogueOrdenarLaMesillaYLosCables =>
      'Ordenar la mesilla y los cables';

  @override
  String get catalogueLimpiarLosEspejosDelArmario =>
      'Limpiar los espejos del armario';

  @override
  String get cataloguePasarLaAspiradoraAlSalon =>
      'Pasar la aspiradora al salón';

  @override
  String get catalogueFregarElSueloDelSalon => 'Fregar el suelo del salón';

  @override
  String get catalogueQuitarElPolvoDeLasEstanterias =>
      'Quitar el polvo de las estanterías';

  @override
  String get catalogueAspirarElSofaYLosCojines =>
      'Aspirar el sofá y los cojines';

  @override
  String get catalogueOrdenarElMuebleDeCablesYCargadores =>
      'Ordenar el mueble de cables y cargadores';

  @override
  String get catalogueLimpiarLaMesaDeCentroYLosMandos =>
      'Limpiar la mesa de centro y los mandos';

  @override
  String get catalogueLimpiarLaPantallaDelTelevisor =>
      'Limpiar la pantalla del televisor';

  @override
  String get catalogueBarrerYFregarLaEntrada => 'Barrer y fregar la entrada';

  @override
  String get catalogueOrdenarLosZapatosDelRecibidor =>
      'Ordenar los zapatos del recibidor';

  @override
  String get catalogueBarrerElBalconOLaTerraza =>
      'Barrer el balcón o la terraza';

  @override
  String get catalogueLimpiarElFiltroDeLaLavadora =>
      'Limpiar el filtro de la lavadora';

  @override
  String get catalogueLimpiarElCuboDeLaBasuraPorDentro =>
      'Limpiar el cubo de la basura por dentro';

  @override
  String get catalogueRevisarYRegarLasPlantas => 'Revisar y regar las plantas';

  @override
  String get catalogueRepasarElEspejoYLaConsolaDeLaEntrada =>
      'Repasar el espejo y la consola de la entrada';

  @override
  String get catalogueLimpiarLosCristalesDeUnaHabitacion =>
      'Limpiar los cristales de una habitación';

  @override
  String get catalogueLimpiarLasMosquiterasYLosRielesDeLasVentanas =>
      'Limpiar las mosquiteras y los rieles de las ventanas';

  @override
  String get catalogueLimpiarElHorno => 'Limpiar el horno';

  @override
  String get catalogueRevisarYOrganizarElCongelador =>
      'Revisar y organizar el congelador';

  @override
  String get catalogueDescalcificarLosGrifos => 'Descalcificar los grifos';

  @override
  String get catalogueRepasarLasJuntasDeLaDucha =>
      'Repasar las juntas de la ducha';

  @override
  String get catalogueLimpiarLosRodapiesDeUnaHabitacion =>
      'Limpiar los rodapiés de una habitación';

  @override
  String get catalogueLimpiarLasPuertasYLosMarcos =>
      'Limpiar las puertas y los marcos';

  @override
  String get catalogueLimpiarLasLamparasYLasPantallas =>
      'Limpiar las lámparas y las pantallas';

  @override
  String get catalogueAspirarDetrasDeUnMuebleGrande =>
      'Aspirar detrás de un mueble grande';

  @override
  String get catalogueRevisarElBotiquinYTirarLoCaducado =>
      'Revisar el botiquín y tirar lo caducado';

  @override
  String get catalogueLimpiarElInteriorDelCoche =>
      'Limpiar el interior del coche';

  @override
  String get catalogueLimpiarElFiltroDelAireAcondicionado =>
      'Limpiar el filtro del aire acondicionado';

  @override
  String get catalogueLimpiarElFiltroDelLavavajillas =>
      'Limpiar el filtro del lavavajillas';

  @override
  String get cataloguePonerALavarLasFundasDeLosCojines =>
      'Poner a lavar las fundas de los cojines';
}
