// Generated by gen_l10n. Do not edit.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'app_strings_es.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of AppStrings
/// returned by `AppStrings.of(context)`.
///
/// Applications need to include `AppStrings.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'strings/app_strings.dart';
///
/// return MaterialApp(
///   localizationsDelegates: AppStrings.localizationsDelegates,
///   supportedLocales: AppStrings.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the AppStrings.supportedLocales
/// property.
abstract class AppStrings {
  AppStrings(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AppStrings of(BuildContext context) {
    return Localizations.of<AppStrings>(context, AppStrings)!;
  }

  static const LocalizationsDelegate<AppStrings> delegate =
      _AppStringsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[Locale('es')];

  /// {components.action-primary} — the one recommended action. Say what happened.
  ///
  /// In es, this message translates to:
  /// **'Hecho'**
  String get actionDone;

  /// Completion acknowledgement — the explicit narrow exclamation exception; reserved solely for after Hecho.
  ///
  /// In es, this message translates to:
  /// **'¡Buen trabajo!'**
  String get completionAcknowledgement;

  /// {components.action-secondary} — one control carrying two features: Otra más fácil is Rescue Mode (FR-5), Ahora no the guilt-free skip (FR-3). Never split, never shortened, never ellipsized; the 200% fold is accepted and verified on a real device.
  ///
  /// In es, this message translates to:
  /// **'Otra más fácil / Ahora no'**
  String get actionRescueOrSkip;

  /// {components.duration-chip} / pocket trigger — carries the standing declared pocket while a pocketed session is open, else the 15 default; tapping declares a session pocket and re-filters the pool. Never a countdown, never remaining minutes; the singular is the ICU plural form, one atomic numeral substituted into an otherwise fixed sentence.
  ///
  /// In es, this message translates to:
  /// **'{minutes, plural, =1 {Tengo un minuto ahora} other {Tengo {minutes} minutos ahora}}'**
  String pocketTrigger(int minutes);

  /// The measured sample task, {typography.task} — the string the 26sp hero size was measured against.
  ///
  /// In es, this message translates to:
  /// **'Despeja la mesa del salón'**
  String get sampleTask;

  /// Dispenser zone-marker label (A12.4) — weekly zone Z1, the canonical cluster name, never a word the card invents.
  ///
  /// In es, this message translates to:
  /// **'Cocina y despensa'**
  String get zoneZ1;

  /// Dispenser zone-marker label (A12.4) — weekly zone Z2, the canonical cluster name.
  ///
  /// In es, this message translates to:
  /// **'Baños'**
  String get zoneZ2;

  /// Dispenser zone-marker label (A12.4) — weekly zone Z3, the canonical cluster name.
  ///
  /// In es, this message translates to:
  /// **'Dormitorios'**
  String get zoneZ3;

  /// Dispenser zone-marker label (A12.4) — weekly zone Z4, the canonical cluster name.
  ///
  /// In es, this message translates to:
  /// **'Salón y zonas comunes'**
  String get zoneZ4;

  /// Dispenser zone-marker label (A12.4) — weekly zone Z5, the canonical cluster name.
  ///
  /// In es, this message translates to:
  /// **'Entrada, lavadero y exteriores'**
  String get zoneZ5;

  /// Duration chip, whole minutes — {formats.duration}: value + non-breaking space + unit. The chip is the cost-before-ask eyebrow; the NBSP is load-bearing at 200%.
  ///
  /// In es, this message translates to:
  /// **'{minutes} min'**
  String durationMinutes(int minutes);

  /// Duration chip, seconds — {formats.duration}: value + non-breaking space + unit, for estimates under a whole minute.
  ///
  /// In es, this message translates to:
  /// **'{seconds} s'**
  String durationSeconds(int seconds);

  /// Duration chip, the Focus Chunk's range — {formats.duration}: en dash + non-breaking space + unit. The one label the duration format family lacked (Story 3.2): the size-option pill for the 10–15 min size, never the internal taxonomy name.
  ///
  /// In es, this message translates to:
  /// **'10–15 min'**
  String get durationFocusRange;

  /// 3-Destination Flow, first choice — the box glyph's meaning.
  ///
  /// In es, this message translates to:
  /// **'Quedármelo'**
  String get destinationKeep;

  /// 3-Destination Flow, second choice — the bag glyph's meaning.
  ///
  /// In es, this message translates to:
  /// **'Donar o vender'**
  String get destinationDonate;

  /// 3-Destination Flow, third choice — the seed glyph's meaning. A confirmed, intentional change from the PRD's original Tirar o reciclar: soltar dodges both the deletion vocabulary and the compliance vocabulary.
  ///
  /// In es, this message translates to:
  /// **'Tirar o soltar'**
  String get destinationRelease;

  /// Cumulative impact dashboard — the volume figure. It carries no glyph (the glyph-adjacency rule) and no denominator.
  ///
  /// In es, this message translates to:
  /// **'≈ 3 cajas liberadas'**
  String get liberatedVolume;

  /// Sunday self-report, ambient and dismissible; persists until answered, never notified.
  ///
  /// In es, this message translates to:
  /// **'Esta semana, ¿cuánto te ha agobiado la casa?'**
  String get weeklySelfReportQuestion;

  /// Ambient Invitation rotating notification set — copy must never acquire task content, counters or urgency.
  ///
  /// In es, this message translates to:
  /// **'Si no tienes nada que hacer, tengo un trabajillo para ti'**
  String get ambientInvitationStorage;

  /// Ambient Invitation rotating notification set.
  ///
  /// In es, this message translates to:
  /// **'Hay algo en la casa que se puede mejorar'**
  String get ambientInvitationImprovement;

  /// Ambient Invitation rotating notification set.
  ///
  /// In es, this message translates to:
  /// **'Con solo 15 minutos podemos avanzar'**
  String get ambientInvitationPocket;

  /// Ambient Invitation rotating notification set.
  ///
  /// In es, this message translates to:
  /// **'Si necesitas cambiar de tarea, te puedo ayudar'**
  String get ambientInvitationTaskChange;

  /// Ambient Invitation rotating notification set.
  ///
  /// In es, this message translates to:
  /// **'Te puedes tomar un respiro de 15 minutos haciendo otras cosas'**
  String get ambientInvitationBreak;

  /// Anti-Marathon checkpoint — the primary permission to stop (FR-10).
  ///
  /// In es, this message translates to:
  /// **'Nada más por el momento'**
  String get checkpointStop;

  /// Anti-Marathon checkpoint — the silent secondary action, never highlighted or animated.
  ///
  /// In es, this message translates to:
  /// **'Quiero seguir'**
  String get checkpointContinue;

  /// Warm Return — appears without backlog or any reference to missed days; the days away are not representable.
  ///
  /// In es, this message translates to:
  /// **'Siempre a tu disposición'**
  String get warmReturnGreeting;

  /// Session close on pool exhaustion (FR-3) — neutral, warm; never an error, never an empty state styled as absence or debt. Part of the SM-C2 audit table.
  ///
  /// In es, this message translates to:
  /// **'por hoy no hay nada más que merezca la pena'**
  String get poolExhaustedClose;

  /// No-Slicer surface · no key configured — an objective problem of the app, not of the home: state the fact, name the remedy, no cushioning.
  ///
  /// In es, this message translates to:
  /// **'No hay clave de IA guardada. Crear un proyecto a partir de una foto necesita una; puedes añadirla en Ajustes.'**
  String get noSlicerNoKey;

  /// No-Slicer surface · invalid key — the rewrite of the PRD's flagged `tu clave no es válida`: the shaming lived in the possessive, not in the judgment.
  ///
  /// In es, this message translates to:
  /// **'La clave guardada no es válida. Puedes revisarla en Ajustes.'**
  String get noSlicerInvalidKey;

  /// No-Slicer surface · exhausted quota — scopes exactly what is unavailable; none of the seven implies the whole product is degraded.
  ///
  /// In es, this message translates to:
  /// **'El crédito de la clave se ha agotado. Se repone en la cuenta del proveedor, no en la app.'**
  String get noSlicerQuotaExhausted;

  /// No-Slicer surface · provider unreachable.
  ///
  /// In es, this message translates to:
  /// **'El servicio de IA no responde ahora mismo. Puedes intentarlo más tarde.'**
  String get noSlicerUnreachable;

  /// No-Slicer surface · no network — precision carries FR-29's plainness requirement: los servicios que usan IA, not the product.
  ///
  /// In es, this message translates to:
  /// **'El móvil está sin conexión. Los servicios que usan IA no son accesibles.'**
  String get noSlicerOffline;

  /// No-Slicer surface · consent declined — the one deliberate deviation: it names no remedy, because the remedy would be retry-and-accept, the persuasion the PRD forbids. Anotarlo is the way forward.
  ///
  /// In es, this message translates to:
  /// **'La foto no se ha enviado.'**
  String get noSlicerConsentDeclined;

  /// No-Slicer surface · person detected in frame — refused on-device, before any upload; the refusal is about the frame, never about the user.
  ///
  /// In es, this message translates to:
  /// **'Se ve una persona en la foto, así que no se ha enviado a ningún sitio. Puedes repetirla sin nadie en el encuadre.'**
  String get personInFrame;

  /// Per-scan consent gate — the one parameterized localized body: the named provider, the scan image and a prompt, nothing else. Declining costs the same number of taps as accepting.
  ///
  /// In es, this message translates to:
  /// **'La foto se procesará por {provider} para obtener las tareas necesarias.'**
  String consentGateBody(String provider);

  /// Per-scan consent gate — first, unfavourable slot; the reading-order residual is recorded, not solved.
  ///
  /// In es, this message translates to:
  /// **'Enviar la foto'**
  String get consentGateSend;

  /// Per-scan consent gate — identical weight to Enviar: no fill, no delay, no confirmation.
  ///
  /// In es, this message translates to:
  /// **'No enviarla'**
  String get consentGateDecline;

  /// Scan wait, with an indeterminate animated pencil writing. No latency cap and deliberately no timeout.
  ///
  /// In es, this message translates to:
  /// **'Creando tareas'**
  String get scanWaitTitle;

  /// No-Slicer surface — the single exit, to Manual Capture.
  ///
  /// In es, this message translates to:
  /// **'Anotarlo'**
  String get noSlicerExit;

  /// Dispenser — the quiet text departure, opening the empty intermediate carrier whose only content is the Ajustes way-out. Prose, not a glyph: on the Dispenser, mass means work and prose means leaving.
  ///
  /// In es, this message translates to:
  /// **'Nuevo proyecto'**
  String get newProjectLink;

  /// Dispenser chrome — the quiet stop (FR-9, UX-DR43): one tap, any moment, any reason; the first-person mirror of the checkpoint's Quiero seguir. Never disabled, never suggested; the warm close is its whole presentation.
  ///
  /// In es, this message translates to:
  /// **'Quiero parar'**
  String get actionStop;

  /// The quiet text way-out inside the Nuevo proyecto surface — the only route into Settings, and with it the validator surface (NFR3, AD-26). Same prose grammar as the Dispenser footer; never a glyph, never emphasised.
  ///
  /// In es, this message translates to:
  /// **'Ajustes'**
  String get settingsWayOut;

  /// Settings — the first group header of the flat platform list (UX-DR33), holding the Time Bag. Quiet support copy, ink-secondary.
  ///
  /// In es, this message translates to:
  /// **'Tu día'**
  String get settingsGroupYourDay;

  /// Settings, Tu día group — the Time Bag row label: the daily minutes the user commits, a ceiling for advance work only. Below 10 minutes the day composes without a Focus Chunk, silently; nothing anywhere names that absence.
  ///
  /// In es, this message translates to:
  /// **'Bolsa de tiempo'**
  String get settingsTimeBag;

  /// Typed project genesis — the consent action, with no provider name and no separate dialog.
  ///
  /// In es, this message translates to:
  /// **'Analizar'**
  String get genesisAnalyze;

  /// Typed project genesis — the quiet way out.
  ///
  /// In es, this message translates to:
  /// **'Volver'**
  String get genesisBack;

  /// One-time first-run curation invitation — appears once ever, never returns once dismissed.
  ///
  /// In es, this message translates to:
  /// **'Ajustar grupos de tareas'**
  String get curationInvitation;

  /// Transformation reward when no Before photo exists — no one-plate diff, no placeholder.
  ///
  /// In es, this message translates to:
  /// **'Un trabajo estupendo'**
  String get rewardWithoutPhoto;

  /// The only labels on a Before/After pair, outside the frames. No caption, no adjective, no sharing.
  ///
  /// In es, this message translates to:
  /// **'Antes'**
  String get rewardLabelBefore;

  /// The only labels on a Before/After pair, outside the frames.
  ///
  /// In es, this message translates to:
  /// **'Después'**
  String get rewardLabelAfter;

  /// Snowball suggestion dismissal.
  ///
  /// In es, this message translates to:
  /// **'Está bien así.'**
  String get snowballDismissAcknowledgement;

  /// Energy check-in — the daily ambient strip, first opening; exists to ask for less, never a gate.
  ///
  /// In es, this message translates to:
  /// **'¿Cuánta energía tienes hoy?'**
  String get energyCheckInQuestion;

  /// Energy check-in — the first battery mark's label (🟢, the standing default). Spoken by semantics; never rendered as text beside the mark.
  ///
  /// In es, this message translates to:
  /// **'Llena'**
  String get energyLevelFull;

  /// Energy check-in — the second battery mark's label (🟡). Spoken by semantics; never rendered as text beside the mark. Filters nothing.
  ///
  /// In es, this message translates to:
  /// **'Media'**
  String get energyLevelMedium;

  /// Energy check-in — the third battery mark's label (🔴). Spoken by semantics; never rendered as text beside the mark. Narrows the next deal to instant-tier only.
  ///
  /// In es, this message translates to:
  /// **'Baja'**
  String get energyLevelLow;

  /// Ambient strip — the ✕ dismissal's label, spoken by semantics only; the mark itself is line-only. Its scope belongs to the resident: the check-in stays hidden for the day, while the weekly report stays hidden for the current opening.
  ///
  /// In es, this message translates to:
  /// **'Cerrar'**
  String get ambientStripDismiss;

  /// End label of the Sunday self-report's 1–5 numeric scale — zero ambiguity.
  ///
  /// In es, this message translates to:
  /// **'Nada'**
  String get selfReportScaleLow;

  /// End label of the Sunday self-report's 1–5 numeric scale.
  ///
  /// In es, this message translates to:
  /// **'Muchísimo'**
  String get selfReportScaleHigh;

  /// Sunday self-report — one 1–5 scale numeral, rendered as its own 48dp tap target in the figure role. The digits are not string literals (AD-15, the mockup's own rule): each passes through this one int placeholder, the duration format's atomic-numeral precedent. Spoken by the digit target's semantics; never composed with any other string.
  ///
  /// In es, this message translates to:
  /// **'{value}'**
  String selfReportScaleValue(int value);

  /// Manual Capture — title, names a place (the spatial frame, rule 1).
  ///
  /// In es, this message translates to:
  /// **'Un rincón de la casa'**
  String get captureTitle;

  /// Manual Capture — helper, touchable things (the spatial frame, rule 2).
  ///
  /// In es, this message translates to:
  /// **'Una cosa que se pueda señalar con la mano: un cajón, una estantería, una silla, un rincón.'**
  String get captureHelper;

  /// Manual Capture — example, opens with a spatial verb (the spatial frame, rule 3).
  ///
  /// In es, this message translates to:
  /// **'Vaciar la caja de la entrada'**
  String get captureExample;

  /// Manual Capture — field placeholder, naming both modalities (FR-32).
  ///
  /// In es, this message translates to:
  /// **'Escríbelo o dilo en voz alta'**
  String get captureFieldPlaceholder;

  /// Manual Capture — while dictating; prose declares the live state, ink never moves.
  ///
  /// In es, this message translates to:
  /// **'Escuchando…'**
  String get dictationListening;

  /// Manual Capture — confirm, disabled until the line holds text: a blank capture is not a task (FR-27).
  ///
  /// In es, this message translates to:
  /// **'Guardar'**
  String get captureSave;

  /// Manual Capture — the single exit; no Cancelar beside it, and Android's back gesture behaves as Descartar.
  ///
  /// In es, this message translates to:
  /// **'Descartar'**
  String get captureDiscard;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Sacar brillo al fregadero'**
  String get catalogueSacarBrilloAlFregadero;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Hacer la cama'**
  String get catalogueHacerLaCama;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Abrir una ventana a ventilar'**
  String get catalogueAbrirUnaVentanaAVentilar;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Recoger 3 cosas del suelo'**
  String get catalogueRecoger3CosasDelSuelo;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Colgar la toalla'**
  String get catalogueColgarLaToalla;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Repasar el espejo del baño con la toalla usada'**
  String get catalogueRepasarElEspejoDelBanoConLaToallaUsada;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Meter en el lavavajillas lo que hay en el fregadero'**
  String get catalogueMeterEnElLavavajillasLoQueHayEnElFregadero;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Arrancar una lavadora'**
  String get catalogueArrancarUnaLavadora;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Sacar la basura al rellano'**
  String get catalogueSacarLaBasuraAlRellano;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Guardar los zapatos de la entrada'**
  String get catalogueGuardarLosZapatosDeLaEntrada;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Regar una planta'**
  String get catalogueRegarUnaPlanta;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Despejar la mesita de noche'**
  String get catalogueDespejarLaMesitaDeNoche;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Bajar la tapa y repasar el borde del inodoro'**
  String get catalogueBajarLaTapaYRepasarElBordeDelInodoro;

  /// Evergreen catalogue (A12.1) — daily Instant Habit, cluster anclas.
  ///
  /// In es, this message translates to:
  /// **'Vaciar la papelera del baño'**
  String get catalogueVaciarLaPapeleraDelBano;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Poner la mesa'**
  String get cataloguePonerLaMesa;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Recoger la mesa'**
  String get catalogueRecogerLaMesa;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Vaciar el lavavajillas'**
  String get catalogueVaciarElLavavajillas;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Repasar la encimera'**
  String get catalogueRepasarLaEncimera;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Limpiar la placa'**
  String get catalogueLimpiarLaPlaca;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Barrer bajo la mesa del comedor'**
  String get catalogueBarrerBajoLaMesaDelComedor;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Pasar la mopa por la cocina'**
  String get cataloguePasarLaMopaPorLaCocina;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Repasar el lavabo y los grifos'**
  String get catalogueRepasarElLavaboYLosGrifos;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Doblar cinco prendas'**
  String get catalogueDoblarCincoPrendas;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Guardar la compra que quedó fuera'**
  String get catalogueGuardarLaCompraQueQuedoFuera;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Ordenar los cojines y la manta del sofá'**
  String get catalogueOrdenarLosCojinesYLaMantaDelSofa;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Vaciar y aclarar el cubo de reciclaje'**
  String get catalogueVaciarYAclararElCuboDeReciclaje;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Recoger la mesa de centro'**
  String get catalogueRecogerLaMesaDeCentro;

  /// Evergreen catalogue (A12.2) — daily Baseline Upkeep (3 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Sacar la basura orgánica'**
  String get catalogueSacarLaBasuraOrganica;

  /// Evergreen catalogue (A12.3) — daily Baseline Upkeep (10–15 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Lavar los platos a mano'**
  String get catalogueLavarLosPlatosAMano;

  /// Evergreen catalogue (A12.3) — daily Baseline Upkeep (10–15 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Dejar la cocina cerrada'**
  String get catalogueDejarLaCocinaCerrada;

  /// Evergreen catalogue (A12.3) — daily Baseline Upkeep (10–15 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Tender la colada'**
  String get catalogueTenderLaColada;

  /// Evergreen catalogue (A12.3) — daily Baseline Upkeep (10–15 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Doblar y guardar una colada'**
  String get catalogueDoblarYGuardarUnaColada;

  /// Evergreen catalogue (A12.3) — daily Baseline Upkeep (10–15 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Recoger el salón entero'**
  String get catalogueRecogerElSalonEntero;

  /// Evergreen catalogue (A12.3) — daily Baseline Upkeep (10–15 min), cluster sostén.
  ///
  /// In es, this message translates to:
  /// **'Ordenar la entrada y el recibidor'**
  String get catalogueOrdenarLaEntradaYElRecibidor;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z1 · Cocina y despensa).
  ///
  /// In es, this message translates to:
  /// **'Pasar la aspiradora a la cocina'**
  String get cataloguePasarLaAspiradoraALaCocina;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z1 · Cocina y despensa).
  ///
  /// In es, this message translates to:
  /// **'Fregar el suelo de la cocina'**
  String get catalogueFregarElSueloDeLaCocina;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z1 · Cocina y despensa).
  ///
  /// In es, this message translates to:
  /// **'Desengrasar la campana extractora'**
  String get catalogueDesengrasarLaCampanaExtractora;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z1 · Cocina y despensa).
  ///
  /// In es, this message translates to:
  /// **'Vaciar una balda del frigorífico y tirar lo caducado'**
  String get catalogueVaciarUnaBaldaDelFrigorificoYTirarLoCaducado;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z1 · Cocina y despensa).
  ///
  /// In es, this message translates to:
  /// **'Repasar los azulejos detrás de la placa'**
  String get catalogueRepasarLosAzulejosDetrasDeLaPlaca;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z1 · Cocina y despensa).
  ///
  /// In es, this message translates to:
  /// **'Limpiar el microondas por dentro'**
  String get catalogueLimpiarElMicroondasPorDentro;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z1 · Cocina y despensa).
  ///
  /// In es, this message translates to:
  /// **'Limpiar el frigorífico por fuera y los tiradores'**
  String get catalogueLimpiarElFrigorificoPorFueraYLosTiradores;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z1 · Cocina y despensa).
  ///
  /// In es, this message translates to:
  /// **'Ordenar el cajón de los cubiertos'**
  String get catalogueOrdenarElCajonDeLosCubiertos;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z2 · Baños).
  ///
  /// In es, this message translates to:
  /// **'Limpiar la ducha o la bañera'**
  String get catalogueLimpiarLaDuchaOLaBanera;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z2 · Baños).
  ///
  /// In es, this message translates to:
  /// **'Fregar el suelo del baño'**
  String get catalogueFregarElSueloDelBano;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z2 · Baños).
  ///
  /// In es, this message translates to:
  /// **'Ordenar el armario del baño y tirar lo caducado'**
  String get catalogueOrdenarElArmarioDelBanoYTirarLoCaducado;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z2 · Baños).
  ///
  /// In es, this message translates to:
  /// **'Limpiar el inodoro'**
  String get catalogueLimpiarElInodoro;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z2 · Baños).
  ///
  /// In es, this message translates to:
  /// **'Limpiar el espejo y los grifos'**
  String get catalogueLimpiarElEspejoYLosGrifos;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z2 · Baños).
  ///
  /// In es, this message translates to:
  /// **'Cambiar las toallas'**
  String get catalogueCambiarLasToallas;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z2 · Baños).
  ///
  /// In es, this message translates to:
  /// **'Destapar el desagüe de la ducha'**
  String get catalogueDestaparElDesagueDeLaDucha;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z3 · Dormitorios).
  ///
  /// In es, this message translates to:
  /// **'Cambiar las sábanas'**
  String get catalogueCambiarLasSabanas;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z3 · Dormitorios).
  ///
  /// In es, this message translates to:
  /// **'Pasar la aspiradora al dormitorio'**
  String get cataloguePasarLaAspiradoraAlDormitorio;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z3 · Dormitorios).
  ///
  /// In es, this message translates to:
  /// **'Aspirar debajo de la cama'**
  String get catalogueAspirarDebajoDeLaCama;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z3 · Dormitorios).
  ///
  /// In es, this message translates to:
  /// **'Vaciar y airear una balda del armario'**
  String get catalogueVaciarYAirearUnaBaldaDelArmario;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z3 · Dormitorios).
  ///
  /// In es, this message translates to:
  /// **'Quitar el polvo de las superficies'**
  String get catalogueQuitarElPolvoDeLasSuperficies;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z3 · Dormitorios).
  ///
  /// In es, this message translates to:
  /// **'Ordenar la mesilla y los cables'**
  String get catalogueOrdenarLaMesillaYLosCables;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z3 · Dormitorios).
  ///
  /// In es, this message translates to:
  /// **'Limpiar los espejos del armario'**
  String get catalogueLimpiarLosEspejosDelArmario;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z4 · Salón y zonas comunes).
  ///
  /// In es, this message translates to:
  /// **'Pasar la aspiradora al salón'**
  String get cataloguePasarLaAspiradoraAlSalon;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z4 · Salón y zonas comunes).
  ///
  /// In es, this message translates to:
  /// **'Fregar el suelo del salón'**
  String get catalogueFregarElSueloDelSalon;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z4 · Salón y zonas comunes).
  ///
  /// In es, this message translates to:
  /// **'Quitar el polvo de las estanterías'**
  String get catalogueQuitarElPolvoDeLasEstanterias;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z4 · Salón y zonas comunes).
  ///
  /// In es, this message translates to:
  /// **'Aspirar el sofá y los cojines'**
  String get catalogueAspirarElSofaYLosCojines;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z4 · Salón y zonas comunes).
  ///
  /// In es, this message translates to:
  /// **'Ordenar el mueble de cables y cargadores'**
  String get catalogueOrdenarElMuebleDeCablesYCargadores;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z4 · Salón y zonas comunes).
  ///
  /// In es, this message translates to:
  /// **'Limpiar la mesa de centro y los mandos'**
  String get catalogueLimpiarLaMesaDeCentroYLosMandos;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z4 · Salón y zonas comunes).
  ///
  /// In es, this message translates to:
  /// **'Limpiar la pantalla del televisor'**
  String get catalogueLimpiarLaPantallaDelTelevisor;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z5 · Entrada, lavadero y exteriores).
  ///
  /// In es, this message translates to:
  /// **'Barrer y fregar la entrada'**
  String get catalogueBarrerYFregarLaEntrada;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z5 · Entrada, lavadero y exteriores).
  ///
  /// In es, this message translates to:
  /// **'Ordenar los zapatos del recibidor'**
  String get catalogueOrdenarLosZapatosDelRecibidor;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z5 · Entrada, lavadero y exteriores).
  ///
  /// In es, this message translates to:
  /// **'Barrer el balcón o la terraza'**
  String get catalogueBarrerElBalconOLaTerraza;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z5 · Entrada, lavadero y exteriores).
  ///
  /// In es, this message translates to:
  /// **'Limpiar el filtro de la lavadora'**
  String get catalogueLimpiarElFiltroDeLaLavadora;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z5 · Entrada, lavadero y exteriores).
  ///
  /// In es, this message translates to:
  /// **'Limpiar el cubo de la basura por dentro'**
  String get catalogueLimpiarElCuboDeLaBasuraPorDentro;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z5 · Entrada, lavadero y exteriores).
  ///
  /// In es, this message translates to:
  /// **'Revisar y regar las plantas'**
  String get catalogueRevisarYRegarLasPlantas;

  /// Evergreen catalogue (A12.4) — weekly zone routine (Z5 · Entrada, lavadero y exteriores).
  ///
  /// In es, this message translates to:
  /// **'Repasar el espejo y la consola de la entrada'**
  String get catalogueRepasarElEspejoYLaConsolaDeLaEntrada;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar los cristales de una habitación'**
  String get catalogueLimpiarLosCristalesDeUnaHabitacion;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar las mosquiteras y los rieles de las ventanas'**
  String get catalogueLimpiarLasMosquiterasYLosRielesDeLasVentanas;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar el horno'**
  String get catalogueLimpiarElHorno;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Revisar y organizar el congelador'**
  String get catalogueRevisarYOrganizarElCongelador;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Descalcificar los grifos'**
  String get catalogueDescalcificarLosGrifos;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Repasar las juntas de la ducha'**
  String get catalogueRepasarLasJuntasDeLaDucha;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar los rodapiés de una habitación'**
  String get catalogueLimpiarLosRodapiesDeUnaHabitacion;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar las puertas y los marcos'**
  String get catalogueLimpiarLasPuertasYLosMarcos;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar las lámparas y las pantallas'**
  String get catalogueLimpiarLasLamparasYLasPantallas;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Aspirar detrás de un mueble grande'**
  String get catalogueAspirarDetrasDeUnMuebleGrande;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Revisar el botiquín y tirar lo caducado'**
  String get catalogueRevisarElBotiquinYTirarLoCaducado;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar el interior del coche'**
  String get catalogueLimpiarElInteriorDelCoche;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar el filtro del aire acondicionado'**
  String get catalogueLimpiarElFiltroDelAireAcondicionado;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Limpiar el filtro del lavavajillas'**
  String get catalogueLimpiarElFiltroDelLavavajillas;

  /// Evergreen catalogue (A12.5) — monthly/seasonal depth work, cluster fondo.
  ///
  /// In es, this message translates to:
  /// **'Poner a lavar las fundas de los cojines'**
  String get cataloguePonerALavarLasFundasDeLosCojines;
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  Future<AppStrings> load(Locale locale) {
    return SynchronousFuture<AppStrings>(lookupAppStrings(locale));
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['es'].contains(locale.languageCode);

  @override
  bool shouldReload(_AppStringsDelegate old) => false;
}

AppStrings lookupAppStrings(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'es':
      return AppStringsEs();
  }

  throw FlutterError(
    'AppStrings.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
