// Generated by gen_l10n. Do not edit.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'app_strings_es.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of AppStrings
/// returned by `AppStrings.of(context)`.
///
/// Applications need to include `AppStrings.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'strings/app_strings.dart';
///
/// return MaterialApp(
///   localizationsDelegates: AppStrings.localizationsDelegates,
///   supportedLocales: AppStrings.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the AppStrings.supportedLocales
/// property.
abstract class AppStrings {
  AppStrings(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AppStrings of(BuildContext context) {
    return Localizations.of<AppStrings>(context, AppStrings)!;
  }

  static const LocalizationsDelegate<AppStrings> delegate =
      _AppStringsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[Locale('es')];

  /// {components.action-primary} — the one recommended action. Say what happened.
  ///
  /// In es, this message translates to:
  /// **'Hecho'**
  String get actionDone;

  /// Completion acknowledgement — the explicit narrow exclamation exception; reserved solely for after Hecho.
  ///
  /// In es, this message translates to:
  /// **'¡Buen trabajo!'**
  String get completionAcknowledgement;

  /// {components.action-secondary} — one control carrying two features: Otra más fácil is Rescue Mode (FR-5), Ahora no the guilt-free skip (FR-3). Never split, never shortened, never ellipsized; the 200% fold is accepted and verified on a real device.
  ///
  /// In es, this message translates to:
  /// **'Otra más fácil / Ahora no'**
  String get actionRescueOrSkip;

  /// {components.duration-chip} / pocket trigger — declares a session pocket and re-filters the pool.
  ///
  /// In es, this message translates to:
  /// **'Tengo 15 minutos ahora'**
  String get pocketTrigger;

  /// The measured sample task, {typography.task} — the string the 26sp hero size was measured against.
  ///
  /// In es, this message translates to:
  /// **'Despeja la mesa del salón'**
  String get sampleTask;

  /// 3-Destination Flow, first choice — the box glyph's meaning.
  ///
  /// In es, this message translates to:
  /// **'Quedármelo'**
  String get destinationKeep;

  /// 3-Destination Flow, second choice — the bag glyph's meaning.
  ///
  /// In es, this message translates to:
  /// **'Donar o vender'**
  String get destinationDonate;

  /// 3-Destination Flow, third choice — the seed glyph's meaning. A confirmed, intentional change from the PRD's original Tirar o reciclar: soltar dodges both the deletion vocabulary and the compliance vocabulary.
  ///
  /// In es, this message translates to:
  /// **'Tirar o soltar'**
  String get destinationRelease;

  /// Cumulative impact dashboard — the volume figure. It carries no glyph (the glyph-adjacency rule) and no denominator.
  ///
  /// In es, this message translates to:
  /// **'≈ 3 cajas liberadas'**
  String get liberatedVolume;

  /// Sunday self-report, ambient and dismissible; persists until answered, never notified.
  ///
  /// In es, this message translates to:
  /// **'Esta semana, ¿cuánto te ha agobiado la casa?'**
  String get weeklySelfReportQuestion;

  /// Ambient Invitation rotating notification set — copy must never acquire task content, counters or urgency.
  ///
  /// In es, this message translates to:
  /// **'Si no tienes nada que hacer, tengo un trabajillo para ti'**
  String get ambientInvitationStorage;

  /// Ambient Invitation rotating notification set.
  ///
  /// In es, this message translates to:
  /// **'Hay algo en la casa que se puede mejorar'**
  String get ambientInvitationImprovement;

  /// Ambient Invitation rotating notification set.
  ///
  /// In es, this message translates to:
  /// **'Con solo 15 minutos podemos avanzar'**
  String get ambientInvitationPocket;

  /// Ambient Invitation rotating notification set.
  ///
  /// In es, this message translates to:
  /// **'Si necesitas cambiar de tarea, te puedo ayudar'**
  String get ambientInvitationTaskChange;

  /// Ambient Invitation rotating notification set.
  ///
  /// In es, this message translates to:
  /// **'Te puedes tomar un respiro de 15 minutos haciendo otras cosas'**
  String get ambientInvitationBreak;

  /// Anti-Marathon checkpoint — the primary permission to stop (FR-10).
  ///
  /// In es, this message translates to:
  /// **'Nada más por el momento'**
  String get checkpointStop;

  /// Anti-Marathon checkpoint — the silent secondary action, never highlighted or animated.
  ///
  /// In es, this message translates to:
  /// **'Quiero seguir'**
  String get checkpointContinue;

  /// Warm Return — appears without backlog or any reference to missed days; the days away are not representable.
  ///
  /// In es, this message translates to:
  /// **'Siempre a tu disposición'**
  String get warmReturnGreeting;

  /// Session close on pool exhaustion (FR-3) — neutral, warm; never an error, never an empty state styled as absence or debt. Part of the SM-C2 audit table.
  ///
  /// In es, this message translates to:
  /// **'por hoy no hay nada más que merezca la pena'**
  String get poolExhaustedClose;

  /// No-Slicer surface · no key configured — an objective problem of the app, not of the home: state the fact, name the remedy, no cushioning.
  ///
  /// In es, this message translates to:
  /// **'No hay clave de IA guardada. Crear un proyecto a partir de una foto necesita una; puedes añadirla en Ajustes.'**
  String get noSlicerNoKey;

  /// No-Slicer surface · invalid key — the rewrite of the PRD's flagged `tu clave no es válida`: the shaming lived in the possessive, not in the judgment.
  ///
  /// In es, this message translates to:
  /// **'La clave guardada no es válida. Puedes revisarla en Ajustes.'**
  String get noSlicerInvalidKey;

  /// No-Slicer surface · exhausted quota — scopes exactly what is unavailable; none of the seven implies the whole product is degraded.
  ///
  /// In es, this message translates to:
  /// **'El crédito de la clave se ha agotado. Se repone en la cuenta del proveedor, no en la app.'**
  String get noSlicerQuotaExhausted;

  /// No-Slicer surface · provider unreachable.
  ///
  /// In es, this message translates to:
  /// **'El servicio de IA no responde ahora mismo. Puedes intentarlo más tarde.'**
  String get noSlicerUnreachable;

  /// No-Slicer surface · no network — precision carries FR-29's plainness requirement: los servicios que usan IA, not the product.
  ///
  /// In es, this message translates to:
  /// **'El móvil está sin conexión. Los servicios que usan IA no son accesibles.'**
  String get noSlicerOffline;

  /// No-Slicer surface · consent declined — the one deliberate deviation: it names no remedy, because the remedy would be retry-and-accept, the persuasion the PRD forbids. Anotarlo is the way forward.
  ///
  /// In es, this message translates to:
  /// **'La foto no se ha enviado.'**
  String get noSlicerConsentDeclined;

  /// No-Slicer surface · person detected in frame — refused on-device, before any upload; the refusal is about the frame, never about the user.
  ///
  /// In es, this message translates to:
  /// **'Se ve una persona en la foto, así que no se ha enviado a ningún sitio. Puedes repetirla sin nadie en el encuadre.'**
  String get personInFrame;

  /// Per-scan consent gate — the one parameterized localized body: the named provider, the scan image and a prompt, nothing else. Declining costs the same number of taps as accepting.
  ///
  /// In es, this message translates to:
  /// **'La foto se procesará por {provider} para obtener las tareas necesarias.'**
  String consentGateBody(String provider);

  /// Per-scan consent gate — first, unfavourable slot; the reading-order residual is recorded, not solved.
  ///
  /// In es, this message translates to:
  /// **'Enviar la foto'**
  String get consentGateSend;

  /// Per-scan consent gate — identical weight to Enviar: no fill, no delay, no confirmation.
  ///
  /// In es, this message translates to:
  /// **'No enviarla'**
  String get consentGateDecline;

  /// Scan wait, with an indeterminate animated pencil writing. No latency cap and deliberately no timeout.
  ///
  /// In es, this message translates to:
  /// **'Creando tareas'**
  String get scanWaitTitle;

  /// No-Slicer surface — the single exit, to Manual Capture.
  ///
  /// In es, this message translates to:
  /// **'Anotarlo'**
  String get noSlicerExit;

  /// Dispenser — the quiet text departure, opening typed project genesis. Prose, not a glyph: on the Dispenser, mass means work and prose means leaving.
  ///
  /// In es, this message translates to:
  /// **'Nuevo proyecto'**
  String get newProjectLink;

  /// Typed project genesis — the consent action, with no provider name and no separate dialog.
  ///
  /// In es, this message translates to:
  /// **'Analizar'**
  String get genesisAnalyze;

  /// Typed project genesis — the quiet way out.
  ///
  /// In es, this message translates to:
  /// **'Volver'**
  String get genesisBack;

  /// One-time first-run curation invitation — appears once ever, never returns once dismissed.
  ///
  /// In es, this message translates to:
  /// **'Ajustar grupos de tareas'**
  String get curationInvitation;

  /// Transformation reward when no Before photo exists — no one-plate diff, no placeholder.
  ///
  /// In es, this message translates to:
  /// **'Un trabajo estupendo'**
  String get rewardWithoutPhoto;

  /// The only labels on a Before/After pair, outside the frames. No caption, no adjective, no sharing.
  ///
  /// In es, this message translates to:
  /// **'Antes'**
  String get rewardLabelBefore;

  /// The only labels on a Before/After pair, outside the frames.
  ///
  /// In es, this message translates to:
  /// **'Después'**
  String get rewardLabelAfter;

  /// Snowball suggestion dismissal.
  ///
  /// In es, this message translates to:
  /// **'Está bien así.'**
  String get snowballDismissAcknowledgement;

  /// Energy check-in — the daily ambient strip, first opening; exists to ask for less, never a gate.
  ///
  /// In es, this message translates to:
  /// **'¿Cuánta energía tienes hoy?'**
  String get energyCheckInQuestion;

  /// End label of the Sunday self-report's 1–5 numeric scale — zero ambiguity.
  ///
  /// In es, this message translates to:
  /// **'Nada'**
  String get selfReportScaleLow;

  /// End label of the Sunday self-report's 1–5 numeric scale.
  ///
  /// In es, this message translates to:
  /// **'Muchísimo'**
  String get selfReportScaleHigh;

  /// Manual Capture — title, names a place (the spatial frame, rule 1).
  ///
  /// In es, this message translates to:
  /// **'Un rincón de la casa'**
  String get captureTitle;

  /// Manual Capture — helper, touchable things (the spatial frame, rule 2).
  ///
  /// In es, this message translates to:
  /// **'Una cosa que se pueda señalar con la mano: un cajón, una estantería, una silla, un rincón.'**
  String get captureHelper;

  /// Manual Capture — example, opens with a spatial verb (the spatial frame, rule 3).
  ///
  /// In es, this message translates to:
  /// **'Vaciar la caja de la entrada'**
  String get captureExample;

  /// Manual Capture — field placeholder, naming both modalities (FR-32).
  ///
  /// In es, this message translates to:
  /// **'Escríbelo o dilo en voz alta'**
  String get captureFieldPlaceholder;

  /// Manual Capture — while dictating; prose declares the live state, ink never moves.
  ///
  /// In es, this message translates to:
  /// **'Escuchando…'**
  String get dictationListening;

  /// Manual Capture — confirm, disabled until the line holds text: a blank capture is not a task (FR-27).
  ///
  /// In es, this message translates to:
  /// **'Guardar'**
  String get captureSave;

  /// Manual Capture — the single exit; no Cancelar beside it, and Android's back gesture behaves as Descartar.
  ///
  /// In es, this message translates to:
  /// **'Descartar'**
  String get captureDiscard;
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  Future<AppStrings> load(Locale locale) {
    return SynchronousFuture<AppStrings>(lookupAppStrings(locale));
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['es'].contains(locale.languageCode);

  @override
  bool shouldReload(_AppStringsDelegate old) => false;
}

AppStrings lookupAppStrings(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'es':
      return AppStringsEs();
  }

  throw FlutterError(
    'AppStrings.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
