// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by tool/gen_catalogue_lookup.dart from
// assets/evergreen/catalogue.json and lib/l10n/app_es.arb.
// Every catalogue name resolves through a statically present ARB
// key; none is assembled at runtime (AD-16, AD-15).

import '../strings/app_strings.dart';

/// The bundle path of the shipped Evergreen catalogue (AD-16).
const String catalogueAssetPath = 'assets/evergreen/catalogue.json';

/// The static catalogue id → AppStrings getter table. The shell loader
/// resolves each entry’s Spanish name through it at load time and hands
/// the core inert data — no key is ever computed at runtime.
final Map<String, String Function(AppStrings strings)> catalogueNameOf =
    Map.unmodifiable(<String, String Function(AppStrings strings)>{
      'sacar-brillo-al-fregadero': (strings) =>
          strings.catalogueSacarBrilloAlFregadero,
      'hacer-la-cama': (strings) => strings.catalogueHacerLaCama,
      'abrir-una-ventana-a-ventilar': (strings) =>
          strings.catalogueAbrirUnaVentanaAVentilar,
      'recoger-3-cosas-del-suelo': (strings) =>
          strings.catalogueRecoger3CosasDelSuelo,
      'colgar-la-toalla': (strings) => strings.catalogueColgarLaToalla,
      'repasar-el-espejo-del-bano-con-la-toalla-usada': (strings) =>
          strings.catalogueRepasarElEspejoDelBanoConLaToallaUsada,
      'meter-en-el-lavavajillas-lo-que-hay-en-el-fregadero': (strings) =>
          strings.catalogueMeterEnElLavavajillasLoQueHayEnElFregadero,
      'arrancar-una-lavadora': (strings) =>
          strings.catalogueArrancarUnaLavadora,
      'sacar-la-basura-al-rellano': (strings) =>
          strings.catalogueSacarLaBasuraAlRellano,
      'guardar-los-zapatos-de-la-entrada': (strings) =>
          strings.catalogueGuardarLosZapatosDeLaEntrada,
      'regar-una-planta': (strings) => strings.catalogueRegarUnaPlanta,
      'despejar-la-mesita-de-noche': (strings) =>
          strings.catalogueDespejarLaMesitaDeNoche,
      'bajar-la-tapa-y-repasar-el-borde-del-inodoro': (strings) =>
          strings.catalogueBajarLaTapaYRepasarElBordeDelInodoro,
      'vaciar-la-papelera-del-bano': (strings) =>
          strings.catalogueVaciarLaPapeleraDelBano,
      'poner-la-mesa': (strings) => strings.cataloguePonerLaMesa,
      'recoger-la-mesa': (strings) => strings.catalogueRecogerLaMesa,
      'vaciar-el-lavavajillas': (strings) =>
          strings.catalogueVaciarElLavavajillas,
      'repasar-la-encimera': (strings) => strings.catalogueRepasarLaEncimera,
      'limpiar-la-placa': (strings) => strings.catalogueLimpiarLaPlaca,
      'barrer-bajo-la-mesa-del-comedor': (strings) =>
          strings.catalogueBarrerBajoLaMesaDelComedor,
      'pasar-la-mopa-por-la-cocina': (strings) =>
          strings.cataloguePasarLaMopaPorLaCocina,
      'repasar-el-lavabo-y-los-grifos': (strings) =>
          strings.catalogueRepasarElLavaboYLosGrifos,
      'doblar-cinco-prendas': (strings) => strings.catalogueDoblarCincoPrendas,
      'guardar-la-compra-que-quedo-fuera': (strings) =>
          strings.catalogueGuardarLaCompraQueQuedoFuera,
      'ordenar-los-cojines-y-la-manta-del-sofa': (strings) =>
          strings.catalogueOrdenarLosCojinesYLaMantaDelSofa,
      'vaciar-y-aclarar-el-cubo-de-reciclaje': (strings) =>
          strings.catalogueVaciarYAclararElCuboDeReciclaje,
      'recoger-la-mesa-de-centro': (strings) =>
          strings.catalogueRecogerLaMesaDeCentro,
      'sacar-la-basura-organica': (strings) =>
          strings.catalogueSacarLaBasuraOrganica,
      'lavar-los-platos-a-mano': (strings) =>
          strings.catalogueLavarLosPlatosAMano,
      'dejar-la-cocina-cerrada': (strings) =>
          strings.catalogueDejarLaCocinaCerrada,
      'tender-la-colada': (strings) => strings.catalogueTenderLaColada,
      'doblar-y-guardar-una-colada': (strings) =>
          strings.catalogueDoblarYGuardarUnaColada,
      'recoger-el-salon-entero': (strings) =>
          strings.catalogueRecogerElSalonEntero,
      'ordenar-la-entrada-y-el-recibidor': (strings) =>
          strings.catalogueOrdenarLaEntradaYElRecibidor,
      'pasar-la-aspiradora-a-la-cocina': (strings) =>
          strings.cataloguePasarLaAspiradoraALaCocina,
      'fregar-el-suelo-de-la-cocina': (strings) =>
          strings.catalogueFregarElSueloDeLaCocina,
      'desengrasar-la-campana-extractora': (strings) =>
          strings.catalogueDesengrasarLaCampanaExtractora,
      'vaciar-una-balda-del-frigorifico-y-tirar-lo-caducado': (strings) =>
          strings.catalogueVaciarUnaBaldaDelFrigorificoYTirarLoCaducado,
      'repasar-los-azulejos-detras-de-la-placa': (strings) =>
          strings.catalogueRepasarLosAzulejosDetrasDeLaPlaca,
      'limpiar-el-microondas-por-dentro': (strings) =>
          strings.catalogueLimpiarElMicroondasPorDentro,
      'limpiar-el-frigorifico-por-fuera-y-los-tiradores': (strings) =>
          strings.catalogueLimpiarElFrigorificoPorFueraYLosTiradores,
      'ordenar-el-cajon-de-los-cubiertos': (strings) =>
          strings.catalogueOrdenarElCajonDeLosCubiertos,
      'limpiar-la-ducha-o-la-banera': (strings) =>
          strings.catalogueLimpiarLaDuchaOLaBanera,
      'fregar-el-suelo-del-bano': (strings) =>
          strings.catalogueFregarElSueloDelBano,
      'ordenar-el-armario-del-bano-y-tirar-lo-caducado': (strings) =>
          strings.catalogueOrdenarElArmarioDelBanoYTirarLoCaducado,
      'limpiar-el-inodoro': (strings) => strings.catalogueLimpiarElInodoro,
      'limpiar-el-espejo-y-los-grifos': (strings) =>
          strings.catalogueLimpiarElEspejoYLosGrifos,
      'cambiar-las-toallas': (strings) => strings.catalogueCambiarLasToallas,
      'destapar-el-desague-de-la-ducha': (strings) =>
          strings.catalogueDestaparElDesagueDeLaDucha,
      'cambiar-las-sabanas': (strings) => strings.catalogueCambiarLasSabanas,
      'pasar-la-aspiradora-al-dormitorio': (strings) =>
          strings.cataloguePasarLaAspiradoraAlDormitorio,
      'aspirar-debajo-de-la-cama': (strings) =>
          strings.catalogueAspirarDebajoDeLaCama,
      'vaciar-y-airear-una-balda-del-armario': (strings) =>
          strings.catalogueVaciarYAirearUnaBaldaDelArmario,
      'quitar-el-polvo-de-las-superficies': (strings) =>
          strings.catalogueQuitarElPolvoDeLasSuperficies,
      'ordenar-la-mesilla-y-los-cables': (strings) =>
          strings.catalogueOrdenarLaMesillaYLosCables,
      'limpiar-los-espejos-del-armario': (strings) =>
          strings.catalogueLimpiarLosEspejosDelArmario,
      'pasar-la-aspiradora-al-salon': (strings) =>
          strings.cataloguePasarLaAspiradoraAlSalon,
      'fregar-el-suelo-del-salon': (strings) =>
          strings.catalogueFregarElSueloDelSalon,
      'quitar-el-polvo-de-las-estanterias': (strings) =>
          strings.catalogueQuitarElPolvoDeLasEstanterias,
      'aspirar-el-sofa-y-los-cojines': (strings) =>
          strings.catalogueAspirarElSofaYLosCojines,
      'ordenar-el-mueble-de-cables-y-cargadores': (strings) =>
          strings.catalogueOrdenarElMuebleDeCablesYCargadores,
      'limpiar-la-mesa-de-centro-y-los-mandos': (strings) =>
          strings.catalogueLimpiarLaMesaDeCentroYLosMandos,
      'limpiar-la-pantalla-del-televisor': (strings) =>
          strings.catalogueLimpiarLaPantallaDelTelevisor,
      'barrer-y-fregar-la-entrada': (strings) =>
          strings.catalogueBarrerYFregarLaEntrada,
      'ordenar-los-zapatos-del-recibidor': (strings) =>
          strings.catalogueOrdenarLosZapatosDelRecibidor,
      'barrer-el-balcon-o-la-terraza': (strings) =>
          strings.catalogueBarrerElBalconOLaTerraza,
      'limpiar-el-filtro-de-la-lavadora': (strings) =>
          strings.catalogueLimpiarElFiltroDeLaLavadora,
      'limpiar-el-cubo-de-la-basura-por-dentro': (strings) =>
          strings.catalogueLimpiarElCuboDeLaBasuraPorDentro,
      'revisar-y-regar-las-plantas': (strings) =>
          strings.catalogueRevisarYRegarLasPlantas,
      'repasar-el-espejo-y-la-consola-de-la-entrada': (strings) =>
          strings.catalogueRepasarElEspejoYLaConsolaDeLaEntrada,
      'limpiar-los-cristales-de-una-habitacion': (strings) =>
          strings.catalogueLimpiarLosCristalesDeUnaHabitacion,
      'limpiar-las-mosquiteras-y-los-rieles-de-las-ventanas': (strings) =>
          strings.catalogueLimpiarLasMosquiterasYLosRielesDeLasVentanas,
      'limpiar-el-horno': (strings) => strings.catalogueLimpiarElHorno,
      'revisar-y-organizar-el-congelador': (strings) =>
          strings.catalogueRevisarYOrganizarElCongelador,
      'descalcificar-los-grifos': (strings) =>
          strings.catalogueDescalcificarLosGrifos,
      'repasar-las-juntas-de-la-ducha': (strings) =>
          strings.catalogueRepasarLasJuntasDeLaDucha,
      'limpiar-los-rodapies-de-una-habitacion': (strings) =>
          strings.catalogueLimpiarLosRodapiesDeUnaHabitacion,
      'limpiar-las-puertas-y-los-marcos': (strings) =>
          strings.catalogueLimpiarLasPuertasYLosMarcos,
      'limpiar-las-lamparas-y-las-pantallas': (strings) =>
          strings.catalogueLimpiarLasLamparasYLasPantallas,
      'aspirar-detras-de-un-mueble-grande': (strings) =>
          strings.catalogueAspirarDetrasDeUnMuebleGrande,
      'revisar-el-botiquin-y-tirar-lo-caducado': (strings) =>
          strings.catalogueRevisarElBotiquinYTirarLoCaducado,
      'limpiar-el-interior-del-coche': (strings) =>
          strings.catalogueLimpiarElInteriorDelCoche,
      'limpiar-el-filtro-del-aire-acondicionado': (strings) =>
          strings.catalogueLimpiarElFiltroDelAireAcondicionado,
      'limpiar-el-filtro-del-lavavajillas': (strings) =>
          strings.catalogueLimpiarElFiltroDelLavavajillas,
      'poner-a-lavar-las-fundas-de-los-cojines': (strings) =>
          strings.cataloguePonerALavarLasFundasDeLosCojines,
    });
